description: iSens, similiar to BarnyWarp, is a BarnyWarp clog that compiles the projects in svelte.
version: 2
updates:
  - package-ecosystem: "npm" # o "bundler", "pip", "maven", ecc.
    directory: "/" # directory del progetto
    schedule:
      interval: "weekly" # o "daily", "monthly"